version: '3.1'

services:
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - color_php:/var/lib/mysql
    command: [
              'mysqld', '--character-set-server=utf8mb4', 
              '--collation-server=utf8mb4_unicode_ci',
              '--default-time-zone=Asia/Bangkok'
            ]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 
    depends_on:
      - db
    links:
      - db
    volumes:
      - /sessions
volumes:
  color_php: